"""
Partial decomposition analysis plotting utilities.

These functions analyze shortened Amber MMPBSA.py partial decomposition files
generated by the preprocessing/PDA workflow.

Inputs:
    Shortened PDA files matching *-c*.dat
    Process labels describing each trajectory set or structure
    Optional residue lists or filtering thresholds

Outputs:
    matplotlib interaction energy plots
"""

import random
from glob import glob

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def _generate_mixed_colors(n, seed=42):
    """
    Generate a reproducible set of distinct plotting colors.

    The colors are drawn from Matplotlib qualitative palettes and shuffled so
    residues next to one another are less likely to receive similar colors.
    """
    colors = (
        list(plt.get_cmap("tab20").colors)
        + list(plt.get_cmap("tab20b").colors)
        + list(plt.get_cmap("tab20c").colors)
    )

    random.seed(seed)
    random.shuffle(colors)

    while len(colors) < n:
        extra = colors.copy()
        random.shuffle(extra)
        colors.extend(extra)

    return colors[:n]


def partial_decomposition_analysis_separate(
    traj_dirs,
    traj_analysis_time,
    processes,
    res_list=None,
    threshold=None,
    threshold_process=None,
    difference=None,
    difference_processes=None,
    example_dir_opt=None,
    example_dir_alt=None,
):
    """
    Compare residue-ligand interaction energies across PDA trajectory sets.

    Each trajectory directory should contain shortened PDA files matching
    *-c*.dat. If multiple files are present, interaction energies are averaged
    across trajectories for that process and pooled standard deviations are
    estimated from the per-file standard deviations.

    A single PDA file can also be included for MD-based comparison.

    The function generates a grouped bar chart for the selected residues.
    """

    if len(traj_dirs) != len(processes):
        raise ValueError("traj_dirs and processes must have the same length.")

    # Choose one example file to determine the ligand residue name and the
    # default list of ligand-interacting residues.
    if example_dir_alt is not None:
        example_dir = example_dir_alt
    elif example_dir_opt is not None:
        example_dir = traj_dirs[example_dir_opt]
    else:
        example_dir = traj_dirs[0]

    example_files = sorted(glob(f"{example_dir}/*-c*.dat"))

    if not example_files:
        raise FileNotFoundError(f"No *-c*.dat files found in {example_dir}.")

    example_file = example_files[0]

    with open(example_file, "r") as f:
        example_lines = f.readlines()

    ligand_name = example_lines[0].split(",")[0].split()[0]

    if ligand_name is None:
        raise ValueError("Could not determine ligand ID from example .dat file.")

    # Use a provided residue list for residues to analyze, 
    # or infer all residues paired with the ligand from the example PDA file.
    if res_list is not None:
        residue_list = [res.strip() for res in res_list]

    else:
        residue_list = []

        for line in example_lines:
            parts = line.split(",")

            if len(parts) < 2:
                continue

            if not parts[0].split():
                continue

            id1 = parts[0]
            id2 = parts[1].strip()
            id1_name = id1.split()[0]

            if (
                id1_name == ligand_name
                and id2 not in residue_list
                and id2.split()[0] != ligand_name
            ):
                residue_list.append(id2)

    residue_aliases = {}

    # Histidine can have multiple residue names depending on protonation state.
    # Treat HID, HIE, and HIP as equivalent for residue matching.
    his_list = ["HID", "HIE", "HIP"]

    for residue in residue_list:
        if residue.split()[0] in his_list:
            residue_number = residue.split()[1]
            residue_aliases[residue] = [
                f"HIE {int(residue_number):>3}",
                f"HID {int(residue_number):>3}",
                f"HIP {int(residue_number):>3}",
            ]
        else:
            residue_aliases[residue] = [residue]

    all_process_df = pd.DataFrame(index=residue_list)

    # Parse each trajectory directory/process independently.
    for traj_dir, process in zip(traj_dirs, processes):

        files = sorted(glob(f"{traj_dir}/*-c*.dat"))
        num_files = len(files)

        if num_files == 0:
            raise FileNotFoundError(f"No *-c*.dat files found in {traj_dir}.")

        total_energies = np.zeros(len(residue_list))
        stdev_numerators = np.zeros(len(residue_list))
        stdev_denominators = np.zeros(len(residue_list))

        if num_files > 1:

            for file in files:

                with open(file, "r") as f:
                    lines = f.readlines()

                energies = []
                stdevs = []

                # Read the ligand-residue pair for each residue of interest.
                for residue in residue_list:
                    interaction_energy = np.nan
                    interaction_stdev = np.nan

                    for line in lines:
                        line_parts = line.split(",")

                        if len(line_parts) < 3:
                            continue

                        if not line_parts[0].split():
                            continue

                        if "Sidechain" in line:
                            break

                        residue_name = line_parts[1].strip()

                        if (
                            line_parts[0].split()[0] == ligand_name
                            and residue_name in residue_aliases[residue]
                        ):
                            interaction_energy = float(line_parts[-3])
                            interaction_stdev = float(line_parts[-2])
                            break

                    energies.append(interaction_energy)
                    stdevs.append(interaction_stdev)

                energies = np.array(energies)
                stdevs = np.array(stdevs)

                total_energies += energies

                # Pool standard deviations across files using the analyzed
                # trajectory length rather than the full trajectory length.
                for i in range(len(stdevs)):
                    if not np.isnan(stdevs[i]):
                        stdev_numerators[i] += (
                            (traj_analysis_time - 1) * (stdevs[i] ** 2)
                        )
                        stdev_denominators[i] += traj_analysis_time - 1

            average_energies = total_energies / num_files

            final_stdevs = []

            for numerator, denominator in zip(stdev_numerators, stdev_denominators):
                if denominator == 0:
                    final_stdevs.append(np.nan)
                else:
                    pooled_variance = numerator / denominator
                    final_stdevs.append(np.sqrt(pooled_variance))

        elif num_files == 1:
            """
            Ligand index will always be 1 for QM/MM dynamics based on 
            required preprocessing and job execution workflow, but indexing
            may be different for MD simulations (with one MMPBSA.py output file
            per MD run)
            """
            file = files[0]
            name = file.replace("-c.dat", "")
            renumbered_file = name + "-r.dat"

            with open(file, "r") as f:
                original_lines = f.readlines()

            with open(renumbered_file, "w") as f:
                for line in original_lines:
                    line_parts = line.split(",")

                    if len(line_parts) < 3 or not line_parts[0].split():
                        f.write(line)
                        continue

                    ligand_id = line_parts[0].split()[0]
                    ligand_number = int(line_parts[0].split()[1])
                    new_ligand_number = str(1)
                    residue_id = line_parts[1].split()[0]
                    old_residue_number = int(line_parts[1].split()[1])
                    remaining_line = line_parts[2:]

                    if old_residue_number < ligand_number:
                        residue_number = old_residue_number + 1
                    else:
                        residue_number = old_residue_number

                    new_ligand = f"{ligand_id} {new_ligand_number:>3}"
                    new_residue = f"{residue_id} {residue_number:>3}"
                    full_line_list = [new_ligand, new_residue] + remaining_line
                    newline = ",".join(full_line_list)
                    f.write(newline)

            with open(renumbered_file, "r") as f:
                lines = f.readlines()

            energies = []
            stdevs = []

            for residue in residue_list:
                interaction_energy = np.nan
                interaction_stdev = np.nan

                for line in lines:
                    line_parts = line.split(",")

                    if len(line_parts) < 3:
                        continue

                    if not line_parts[0].split():
                        continue

                    if "Sidechain" in line:
                        break

                    residue_name = line_parts[1].strip()

                    if residue_name in residue_aliases[residue]:
                        interaction_energy = float(line_parts[-3])
                        interaction_stdev = float(line_parts[-2])
                        break

                energies.append(interaction_energy)
                stdevs.append(interaction_stdev)

            average_energies = energies
            final_stdevs = stdevs

        all_process_df[f"{process} intE"] = average_energies
        all_process_df[f"{process} stddev. intE"] = final_stdevs

    # Filter residues for plotting if a threshold or process difference was requested.
    if res_list is not None and threshold is not None:
        print("Warning: res_list provided. Threshold ignored.")

    if threshold is not None and res_list is None:

        if threshold_process is not None:
            if isinstance(threshold_process, int):
                selected_process = processes[threshold_process]
            else:
                selected_process = threshold_process

        else:
            selected_process = processes[0]
            print(
                "Warning: No process provided for threshold analysis. "
                f"Using first process provided: {selected_process}"
            )
        
        plot_df = all_process_df[
            all_process_df[f"{selected_process} intE"] < threshold
        ]

    elif difference is not None and difference_processes is not None:

        process_1 = difference_processes[0]
        process_2 = difference_processes[1]

        energies_1 = all_process_df[f"{process_1} intE"]
        energies_2 = all_process_df[f"{process_2} intE"]

        selected_residues = []

        for i, (energy_1, energy_2) in enumerate(zip(energies_1, energies_2)):
            if abs(energy_1 - energy_2) >= difference:
                residue_id = residue_list[i]
                selected_residues.append(residue_id)

        plot_df = all_process_df.loc[selected_residues]

    elif (
        (difference is None and difference_processes is not None)
        or
        (difference is not None and difference_processes is None)
    ):
        raise ValueError(
            "Both difference and difference_processes must be defined, "
            "or neither should be."
        )

    else:
        plot_df = all_process_df

    plotted_residues = list(plot_df.index)

    x = np.arange(len(plotted_residues))
    n_processes = len(processes)

    width = 0.8 / n_processes
    offsets = (np.arange(n_processes) - (n_processes - 1) / 2) * width

    colors = _generate_mixed_colors(len(processes))

    plt.figure()

    for offset, process, color in zip(offsets, processes, colors):
        plt.bar(
            x + offset,
            plot_df[f"{process} intE"],
            width=width,
            yerr=plot_df[f"{process} stddev. intE"],
            label=process,
            color=color,
        )

    final_name = "/".join(processes)

    plt.xticks(x, plotted_residues, rotation=45, ha="right")
    plt.legend()

    if threshold is not None:
        plt.title(f"Residue-{final_name} Int. E Values (< {threshold} kcal/mol Only)")
    elif difference is not None and difference_processes is not None:
        plt.title(
            f"Residue-{final_name} Int. E Values "
            f"(difference > {difference} kcal/mol Only)"
        )
    else:
        plt.title(f"Residue-{final_name} Int. E Values")

    plt.xlabel("Residue")
    plt.ylabel("Int. E (kcal/mol)")
    plt.tight_layout()


def _plot_residue_interactions_combined(
    df,
    atol=1e-8,
    top_label=5,
    top_legend=15,
    figsize=(8, 6),
):
    """
    Plot stacked residue interaction energies for multiple processes.

    Each dataframe column is plotted as one stacked bar. Residues are colored
    consistently across processes, and the largest contributors can be labeled
    directly on the bars.
    """
    fig, ax = plt.subplots(figsize=figsize)

    all_residues = df.index.tolist()
    colors = _generate_mixed_colors(len(all_residues))
    color_map = {residue: colors[i] for i, residue in enumerate(all_residues)}

    # Select the globally largest contributors for the legend.
    total_contribution = df.abs().sum(axis=1)
    top_global = (
        total_contribution.sort_values(ascending=False)
        .head(top_legend)
        .index
    )

    for i, column in enumerate(df.columns):
        series = df[column].copy()

        # Remove very small values so the plot focuses on meaningful interactions.
        series = series[~np.isclose(series, 0, atol=atol)]

        # Sort by interaction magnitude for clearer stacked bars.
        series = series.reindex(series.abs().sort_values(ascending=False).index)

        bottom = 0
        top_residues_to_label = series.head(top_label)

        for residue, value in series.items():
            ax.bar(
                i,
                value,
                bottom=bottom,
                edgecolor="black",
                color=color_map[residue],
                label=residue,
            )

            if residue in top_residues_to_label.index:
                y = bottom + value / 2
                ax.text(
                    i,
                    y,
                    residue,
                    ha="center",
                    va="center",
                    fontsize=8,
                )

            bottom += value

    ax.set_xticks(range(len(df.columns)))
    ax.set_xticklabels(df.columns, rotation=90)
    ax.set_ylabel("Int. E (kcal/mol)")
    ax.set_title("Residue Int. E")

    handles, labels = ax.get_legend_handles_labels()

    legend_dict = {}

    for handle, label in zip(handles, labels):
        if label in top_global and label not in legend_dict:
            legend_dict[label] = handle

    ax.legend(
        legend_dict.values(),
        legend_dict.keys(),
        bbox_to_anchor=(1.02, 1),
        loc="upper left",
    )

    plt.tight_layout()
    plt.show()


def partial_decomposition_analysis_combined(
    pda_files,
    processes,
    threshold,
    res_list=None,
):
    """
    Plot summed stabilizing residue interaction energies across PDA files.

    Values weaker than the supplied stabilizing threshold are set to zero.
    The resulting dataframe is plotted as a stacked residue-separated bar 
    chart.
    """
    if len(pda_files) != len(processes):
        raise ValueError("pda_files and processes must have the same length.")

    all_names = []
    all_values = []

    for file in pda_files:

        residue_names = []
        interaction_values = []

        with open(file, "r") as f:
            lines = f.readlines()

        for line in lines:
            line_parts = line.split(",")

            if len(line_parts) < 3:
                continue

            if not line_parts[0].split():
                continue

            residue = line_parts[1].strip()
            value = float(line_parts[-3])

            residue_names.append(residue)

            if res_list is not None:

                if value < -threshold and residue in res_list:
                    interaction_values.append(value)
                else:
                    interaction_values.append(0)

            else:
                if value < -threshold:
                    interaction_values.append(value)
                else:
                    interaction_values.append(0)

        all_names.append(residue_names)
        all_values.append(interaction_values)

    residues = all_names[0]
    df = pd.DataFrame(index=residues)

    for values, process in zip(all_values, processes):
        df[process] = values

    _plot_residue_interactions_combined(df, figsize=(4, 8))
